baseURL = "https://sufishientcharters.com/"
languageCode = "en-us"
title = "SuFISHient Charters"
theme = "hero"

[params]
  google_api_key="AIzaSyAxhi0eUKEbhESQonfdcCqN4GP6bLtGjqw"

  [params.homepage_meta_tags]
    meta_description = "SuFISHient Charters: See photos, check our rates, and book a fishing trip. Sailing out of Holland, Grand Haven, or Saugatuck on beautiful Lake Michigan."
    meta_og_title = "SuFISHient Charters | Book your fishing trip | Holland, Michigan"
    meta_og_type = "website"
    meta_og_url = "https://sufishientcharters.com/"
    meta_og_image = "https://sufishientcharters.com/images/boat.jpg"
    meta_og_description = "SuFISHient Charters: see photos, check our rates, and book a fishing trip. Sailing out of Holland, Grand Haven, or Saugatuck on beautiful Lake Michigan."
    meta_twitter_card = "summary_large_image"
    meta_twitter_image = "https://sufishientcharters.com/images/boat.jpg"
    meta_twitter_site = "@sufishientcharters"
    meta_twitter_creator = "@sufishientcharters"

[[menu.main]]
	name = "Charters"
	url = "/charters/"
    weight = 1

[[menu.main]]
	name = "Photos"
	url = "/photos/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

[[menu.main]]
    name = "Book"
    url = "/book/"
    weight = 5
    [menu.main.params]
        class = "cta"

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
